---
version: '3'

services:
  gamesguru:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./gamesguru:/gamesguru
      - gamesguru-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    volumes:
      - gamesguru-db-data:/var/lib/postgresql/data
      - /db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      - POSTGRES_DB=gamesguru
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  gamesguru-db-data:
  gamesguru-static-data:
