---
version: '3'

services:
  gamesguru:
    build:
      context: .
    restart: always
    volumes:
      - static-data-gamesguru:/vol/web
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - STATIC_URL=/static/static/
      - STATIC_ROOT=vol/web/static
      - ENV=${ENV}
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres-data-gamesguru:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - gamesguru
    ports:
      - "80:8000"  # map port 80 on the server to 8000 on the running container
    volumes:
      - static-data-gamesguru:/vol/web/static

volumes:
  postgres-data-gamesguru:
  static-data-gamesguru:
