---
version: '3'

services:
  gamesguru:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./gamesguru:/gamesguru
      - gamesguru-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ENV=${ENV}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    volumes:
      - gamesguru-db-data:/var/lib/postgresql/data
      - /db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  chromedriver:
    image: selenium/standalone-chrome:112.0-chromedriver-112.0
    restart: always
    container_name: chromedriver
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - gamesguru

volumes:
  gamesguru-db-data:
  gamesguru-static-data:
