---
version: '3'

services:
  gamesguru:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static:/vol/web/static
      - media:/vol/web/media
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - STATIC_URL=/static/static/
      - STATIC_ROOT=vol/web/static
      - ENV=${ENV}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - /db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

#  caddy:
#    image: caddy:2.7
#    restart: unless-stopped
#    depends_on:
#      - gamesguru
#    cap_add:
#      - NET_ADMIN
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - caddy_data:/data
#      - caddy_config:/config
#      - gamesguru-static:/vol/web/static
#      - gamesguru-media:/vol/web/media

volumes:
  db:
  static:
  media:
#  caddy_data:
#  caddy_config:
