---
version: '3'

networks:
  caddy:

volumes:
  db:
  static:
  media:
  caddy_data:
  caddy_config:

services:
  gamesguru:
    container_name: gamesguru
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static:/vol/web/static
      - media:/vol/web/media
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ENV=${ENV}
    depends_on:
      - postgres
    networks:
      - caddy

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - caddy

  caddy:
    container_name: caddy
    image: caddy:2.7
    restart: unless-stopped
    depends_on:
      - gamesguru
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - static:/vol/web/static
      - media:/vol/web/media
    networks:
      - caddy
