ALLOWED_HOSTS = ['146.59.30.182']
CORS_ALLOWED_ORIGINS = [
   "https://gamesguru.pl",
]
CSRF_TRUSTED_ORIGINS = ["https://gamesguru.pl*"]

SECURE_SSL_REDIRECT = True
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
