# Generated by Django 4.2.6 on 2023-10-12 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('4c99fc99-9b10-447a-8590-ceb15553d2f3'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('5f87c4e0-ce39-40ee-b7ae-153c4d0a5cf2'), editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.TextField(max_length=10)),
                ('url', models.TextField(max_length=1000)),
                ('pub_time', models.DateTimeField(verbose_name='Publication time')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.shop')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
