# Generated by Django 4.2.6 on 2023-10-19 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer_remove_product_unique_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='epi',
            field=models.CharField(auto_created=True, default=uuid.uuid4, max_length=36),
        ),
    ]
