# Generated by Django 4.2.6 on 2023-11-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcategory_product_search_name_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_name',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
