# Generated by Django 4.2.6 on 2023-11-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_base_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
