# Generated by Django 4.2.6 on 2023-11-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_base_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_name',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_name',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=100),
        ),
    ]
