# Generated by Django 4.2.6 on 2023-11-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_base_name_alter_product_search_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_lower_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
