# Generated by Django 4.2.6 on 2023-12-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_category_delete_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_words_to_exclude',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='search_words_to_include',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
