# Generated by Django 4.2.6 on 2023-12-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_offer_state_offer_state_check_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='search_words_to_exclude',
            new_name='search_words_any_to_exclude',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='search_words_to_include',
            new_name='search_words_any_to_include',
        ),
        migrations.AddField(
            model_name='product',
            name='search_words_all_to_include',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
