# Generated by Django 4.2.6 on 2024-01-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_shop_show_on_smartphones'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='affiliation',
            field=models.CharField(choices=[('tradedoubler', 'Tradedoubler'), ('convertiser', 'Convertiser')], default='tradedoubler', max_length=20),
        ),
    ]
