# Generated by Django 4.2.6 on 2024-01-28 16:33

from django.db import migrations, models

from gamesguru.products.utils import generate_random_string


def update_epi(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        product.epi = generate_random_string()
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_shop_affiliation'),
    ]

    operations = [
        migrations.RunPython(update_epi),
        migrations.AlterField(
            model_name='product',
            name='epi',
            field=models.CharField(auto_created=True, default=generate_random_string, max_length=32),
        ),
    ]
