# Generated by Django 4.2.6 on 2024-01-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_product_unique_search_name_product_base_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='search_words_all_to_include',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_words_any_to_exclude',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_words_any_to_include',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
