# Generated by Django 4.2.6 on 2024-01-29 19:23
import re

import django.contrib.postgres.fields
from django.db import migrations, models


def to_list(string) -> list[str]:
    elements = re.split(r',', string)
    return [element for element in elements if element]


def propagate_lists(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        product.search_words_all_to_include = to_list(product.search_word_all_to_include)
        product.search_words_any_to_include = to_list(product.search_word_any_to_include)
        product.search_words_any_to_exclude = to_list(product.search_word_any_to_exclude)
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_search_words_all_to_include_product_search_word_all_to_include_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_words_all_to_include',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='search_words_any_to_exclude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='search_words_any_to_include',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), blank=True, default=list, size=None),
        ),
        migrations.RunPython(propagate_lists),
    ]
