# Generated by Django 4.2.6 on 2024-01-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_search_words_all_to_include_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_word_all_to_include',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_word_any_to_exclude',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_word_any_to_include',
        ),
    ]
